### ISSUE TITLE
Saat production data club tidak muncul

### ISSUE THREAD

**Issue by muhyulianto** [dicodingacademy/a163-bfwd-labs#7]
![Screenshot_1](https://user-images.githubusercontent.com/22585843/86418472-704a8800-bcfa-11ea-883f-22defc0b218d.png)
![Screenshot_2](https://user-images.githubusercontent.com/22585843/86418473-717bb500-bcfa-11ea-83f4-6a8b9c58c14f.png)
![Screenshot_3](https://user-images.githubusercontent.com/22585843/86418477-72ace200-bcfa-11ea-8f0a-a8363aff614a.png)

NB: Saya pake live-server apa hal tersebut juga berpengaruh?

**Comment by dimasmds** [comment]
Bisa diarahkan ke forum diskusi yah ^_^
